@url_user = http://localhost:3000/api/user/
@url_task = http://localhost:3000/api/task/

@json_user = Content-Type: application/json
@json_task = content-Type: application/json

###
#POST Register New User
POST {{url_user}}register
{{json_user}}

{
    "name": "Daisy",
    "email": "daisy99@vt.edu",
    "password": "123456",
    "identity": "Admin"
}

###
#GET List All User - Testing
GET {{url_user}}users

###
#POST Login
POST {{url_user}}login
{{json_user}}

{
    "email": "stianyu99@vt.edu",
    "password": "123456"
}

###
#GET Current User Testing
GET {{url_user}}current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjc4NDk2MzEzLCJleHAiOjE2Nzg0OTkzMTN9.4UZiXYBZdsLSJbFM1b5idgLiDXHW-ZdBt8Pw8oNpIoY

##############################################################################################

###
#POST Create a Task
POST {{url_task}}create
{{json_task}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjgyOTkzNDMzLCJleHAiOjE2ODI5OTY0MzN9.qttS9olOzA4sZyaZGDwCTL7e-wQUAq5VxJAto86910U

{
    "userId": "640a6b5b04391ed7d7d8e009",
    "taskName": "Software Engineer Project Proposal",
    "status": "Pending",
    "date": "2023/04/30"
}

###
#GET All Task List by User
GET {{url_task}}taskList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjc4NTIzNTIyLCJleHAiOjE2Nzg1MjY1MjJ9.JJvFffn8WVFARaGp4BU533yXutRX5e6N0ycBQJ4ih-g

###
#PUT Update One of Tasks
PUT {{url_task}}640bd3220f75f293b333bcf6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjc4NTIzNTIyLCJleHAiOjE2Nzg1MjY1MjJ9.JJvFffn8WVFARaGp4BU533yXutRX5e6N0ycBQJ4ih-g
{{json_task}}

{
    "status":"Completed"
}

###
#DELETE Delete one of Tasks
DELETE {{url_task}}640c2286c623ab69df4905ca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjc4NTI0OTkwLCJleHAiOjE2Nzg1Mjc5OTB9.MrG4FVKXsgah_Q1jKqZDQ1WC1cfK1Mb2neMobTyrGUE

###
#Get All Task - Assess Right
GET {{url_task}}allTasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjgzMjcxNjU2LCJleHAiOjE2ODMyNzQ2NTZ9.J_mEnjRC6xjEX27mubgIx4uEYomKupyCcI2LzCSnwRc

###
#Delete Task - Assess Right
DELETE {{url_task}}6454a9b965d575cea1e3b732
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjgzMjcxNjU2LCJleHAiOjE2ODMyNzQ2NTZ9.J_mEnjRC6xjEX27mubgIx4uEYomKupyCcI2LzCSnwRc
