@url = http://localhost:3000/

@json = Content-Type: application/json

###
#POST Register New User
POST {{url}}api/user/register
{{json}}

{
    "name": "Daisy",
    "email": "daisy99@vt.edu",
    "password": "123456",
    "identity": "Admin"
}

###
#GET List All User - Testing
GET {{url}}api/user/users

###
#POST Login
POST {{url}}api/user/login
{{json}}

{
    "email": "stianyu99@vt.edu",
    "password": "123456"
}

###
#GET Current User Testing
GET {{url}}api/user/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjgyOTg4NzkxLCJleHAiOjE2ODI5OTE3OTF9.-BMp41rnljmtCLh1N6uT8MU9BELApP1a6QZ1M_D4gRs